# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 过客小站 HapLeo
lang: zh-cn
email: i@passby.me
description: > # this means to ignore newlines until "baseurl:"
  Node.js 前端 以及 Web相关的一切
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.hapleo.com" # the base hostname & protocol for your site
twitter_username: ahuanclass
github_username:  lgh06

# Build settings
markdown: kramdown
theme: minima

paginate: 25
paginate_path: "/page/:num/"

port: 12000

highlighter: pygments
encoding: utf-8
gems: ["jekyll-paginate"]